---
title: "Overview of the didhetero Methods"
author: "Shunsuke Imai (imai.shunsuke.57n@st.kyoto-u.ac.jp), Lei Qin (qinlei6d@unii.ac.jp), Takahide Yanagi (yanagi@econ.kyoto-u.ac.jp)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of the didhetero Methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 5
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

## Introduction

This vignette provides an overview of estimation and uniform inference methods that can be implemented using the **didhetero** package.

For the sake of brevity, we omit many details of our methods here, which can be found in Imai, Qin, and Yanagi (2025).

## Staggered DiD Setup

We consider essentially the same staggered difference-in-differences (DiD) setup as in Callaway and Sant'Anna (2021).

We have balanced panel data for which we observe the following variables for units $i = 1, \dots, n$ and periods $t = 1, \dots, \mathcal{T}$.

- The outcome variable $Y_{i,t}$.

- The binary treatment $D_{i,t}$ such that $D_{i,1} = 0$ and that $D_{i,t-1} = 1$ implies $D_{i,t} = 1$ for any $t = 3, \dots, \mathcal{T}$.

- The "group" $G_i = \min\{ t : D_{i,t} = 1 \}$ if $D_{i,t} = 1$ for some $t$, and $G_i = 0$ otherwise.

- The $k$-dimensional vector of the pre-treatment covariates $X_i$ that includes a scalar continuous covariate $Z_i$ as an element of particular interest.

## Target Parameters

To examine the heterogeneity in treatment effects with respect to groups, periods, and continuous covariate values, we consider two types of target parameters:

- The group-time conditional average treatment effect (CATT) given $Z = z$.

- The summary parameters that aggregate CATTs with estimable weighting functions. 

CATT is
\begin{equation}
    {\text{CATT}}_{g,t}(z)
    = \mathbb{E} [ Y_{i,t}(g) - Y_{i,t}(0) \mid G_{i,g} = 1, Z_i = z ],
\end{equation}
where $Y_{i,t}(g)$ and $Y_{i,t}(0)$ denote the potential outcomes given $G_i = g$ and $G_i = 0$, respectively, and $z$ is a value of $Z_i$.
Estimating ${\text{CATT}}_{g,t}(z)$ over $(g, t, z)$ is helpful in understanding the treatment effect heterogeneity with respect to group $g$, calendar time $t$, and covariate value $z$.

The aggregated parameter is
\begin{equation}
    \theta(z) 
    = \sum_{g \in \mathcal{G}} \sum_{t=2}^{\mathcal{T}} w_{g,t}(z) \cdot \text{CATT}_{g,t}(z),
\end{equation}
where $\mathcal{G}$ denotes the set of realized treatment timings and $w_{g,t}(z)$ is an estimable weighting function that determines the causal interpretation of this aggregated parameter.

Examples include:

- The event-study-type conditional average treatment effect $\theta_{\text{es}}(e, z)$.

- The group-specific conditional average treatment effect $\theta_{\text{sel}}(g, z)$.

- The calendar-time conditional average treatment effect $\theta_{\text{c}}(t, z)$.

- The simple weighted conditional average treatment effect $\theta_{\text{W}}^{\text{O}}(z)$.



## Doubly Robust Identification, Estimation, and Uniform Inference

We can show that $\text{CATT}_{g,t}(z)$ is identified by a conditional doubly robust (DR) estimand $\text{DR}_{g,t}(z)$, which is a conditional counterpart of the DR estimand in Callaway and Sant'Anna (2021).
This identification result serves as a building block of estimation and uniform inference for CATT and the aggregated parameter.

To perform uniform inference for $\text{CATT}_{g,t}(z)$ over a set of $(g, t, z)$, we can construct a $(1 - \alpha)$ uniform confidence band for $\text{CATT}_{g,t}(z)$ over the set of $(g, t, z)$ by a family of intervals, denoted as $\mathcal{C} = \{ \mathcal{C}_{g,t}(z) \}$ with
\begin{equation}
    \mathcal{C}_{g,t}(z)
    =
    \left[ 
    \widehat{\text{DR}}_{g,t}(z) - c(1 - \alpha) \cdot \widehat{\text{SE}}_{g,t}(z),
    \qquad 
    \widehat{\text{DR}}_{g,t}(z) + c(1 - \alpha) \cdot \widehat{\text{SE}}_{g,t}(z)
    \right],
\end{equation}
where $\widehat{\text{DR}}_{g,t}(z)$ is a three-step estimator computed with certain parametric estimation procedures and nonparametric local polynomial regressions, $\widehat{\text{SE}}_{g,t}(z)$ is a pointwise standard error, and $c(1 - \alpha)$ is a uniform critical value obtained from an analytical method or weighted bootstrapping.

To perform uniform inference for the aggregated parameter, we can construct a $(1 - \alpha)$ uniform confidence band for $\theta(z)$ over the set of $z$ and the variable specific to the summary parameter of interest (e.g., treatment exposure time $e$) by a family of intervals, denoted as $\mathcal{C}_{\theta} = \{ \mathcal{C}_{\theta}(z) \}$ with
\begin{equation}
    \mathcal{C}_{\theta}(z)
    = \left[ \widehat{\theta}(z) - c_{\theta}(1 - \alpha) \cdot \widehat{\text{SE}}_{\theta}(z), \quad \widehat{\theta}(z) + c_{\theta}(1 - \alpha) \cdot \widehat{\text{SE}}_{\theta}(z) \right],
\end{equation}
where $\widehat{\theta}(z)$ is an estimator obtained as an empirical analogue of $\theta(z)$, $\widehat{\text{SE}}_{\theta}(z)$ is a pointwise standard error, and $c_{\theta}(1 - \alpha)$ is a uniform critical value via an analytical method or multiplier bootstrapping.

Importantly, to ensure the validity of uniform inference, the critical value $c(1 - \alpha)$ must not depend on $(g, t, z)$ and is larger than the standard Wald-type pointwise critical value (i.e., the $(1 - \alpha/2)$ quantile of the standard normal distribution).
Similarly, the uniform critical value $c_{\theta}(1 - \alpha)$ should not depend on $z$ and the variable specific to the summary parameter of interest (e.g., treatment exposure time $e$) and is larger than the standard Wald-type pointwise critical value.

## Recommendations

- For constructing the uniformly valid critical value, the bootstrap would work better than the analytical method.

- For the choice of the local polynomial order, the recommended default is `p = 2`.

- For the bandwidth, we recommend different choices depending on the local polynomial order.
When `p = 2`, the recommended default is to use the IMSE-optimal bandwidth for local linear regression (`bwselect = "IMSE1"`).
When `p = 1`, the recommended default is to use the rule-of-thumb undersmoothing for local linear regression (`bwselect = "US1"`).
This is because we need to make bias arising from kernel smoothing asymptotically negligible for justify our uniform confidence bands.
In this view, `bwselect = "IMSE2"` is not recommended.

- Although checking for the heterogeneity in pre-trends is useful for assessing the credibility of the identifying assumptions, doing so may widen the confidence intervals in post-treatment periods. In this view, we set `pretrend = FALSE` as the default.

- To examine the heterogeneity in all key variables and covariate values, the recommended default is `uniformall = TRUE`.

## References

- Callaway, B., & Sant’Anna, P. H. (2021).
Difference-in-differences with multiple time periods.
Journal of Econometrics, 225(2), 200-230.
[Link](https://doi.org/10.1016/j.jeconom.2020.12.001)

- Imai, S., Qin, L., & Yanagi, T. (2025).
Doubly Robust Uniform Confidence Bands for Group-Time Conditional Average Treatment Effects in Difference-in-Differences.
arXiv preprint arXiv:2305.02185.
[Link](https://doi.org/10.48550/arXiv.2305.02185)
